"""add_external_data_models

Revision ID: 27e69189aae6
Revises: eeb4fdd8ebff
Create Date: 2026-05-05 22:55:51.853133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27e69189aae6'
down_revision: Union[str, Sequence[str], None] = 'eeb4fdd8ebff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_data_fetch_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_fetched', sa.Integer(), nullable=True),
    sa.Column('rows_saved', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_data_fetch_logs_job_name'), 'external_data_fetch_logs', ['job_name'], unique=False)
    op.create_index(op.f('ix_external_data_fetch_logs_source'), 'external_data_fetch_logs', ['source'], unique=False)
    op.create_index(op.f('ix_external_data_fetch_logs_status'), 'external_data_fetch_logs', ['status'], unique=False)
    
    op.create_table('external_data_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('series_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('pro_use', sa.String(), nullable=True),
    sa.Column('geography', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'series_id', name='uq_external_series_id')
    )
    op.create_index(op.f('ix_external_data_series_series_id'), 'external_data_series', ['series_id'], unique=False)
    op.create_index(op.f('ix_external_data_series_source'), 'external_data_series', ['source'], unique=False)
    
    op.create_table('external_industry_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('dataset', sa.String(), nullable=True),
    sa.Column('geo_id', sa.String(), nullable=True),
    sa.Column('geo_name', sa.String(), nullable=True),
    sa.Column('industry_id', sa.String(), nullable=True),
    sa.Column('industry_name', sa.String(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'dataset', 'geo_id', 'industry_id', 'metric_name', 'year', 'period', name='uq_external_industry_stat')
    )
    op.create_index(op.f('ix_external_industry_stats_dataset'), 'external_industry_stats', ['dataset'], unique=False)
    op.create_index(op.f('ix_external_industry_stats_geo_id'), 'external_industry_stats', ['geo_id'], unique=False)
    op.create_index(op.f('ix_external_industry_stats_industry_id'), 'external_industry_stats', ['industry_id'], unique=False)
    op.create_index(op.f('ix_external_industry_stats_metric_name'), 'external_industry_stats', ['metric_name'], unique=False)
    op.create_index(op.f('ix_external_industry_stats_source'), 'external_industry_stats', ['source'], unique=False)
    op.create_index(op.f('ix_external_industry_stats_year'), 'external_industry_stats', ['year'], unique=False)
    
    op.create_table('external_trade_flows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('reporter_id', sa.String(), nullable=False),
    sa.Column('reporter_name', sa.String(), nullable=True),
    sa.Column('partner_id', sa.String(), nullable=False),
    sa.Column('partner_name', sa.String(), nullable=True),
    sa.Column('flow_type', sa.String(), nullable=True),
    sa.Column('commodity_id', sa.String(), nullable=True),
    sa.Column('commodity_name', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('trade_value', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'reporter_id', 'partner_id', 'flow_type', 'commodity_id', 'year', 'period', name='uq_external_trade_flow')
    )
    op.create_index(op.f('ix_external_trade_flows_commodity_id'), 'external_trade_flows', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_external_trade_flows_flow_type'), 'external_trade_flows', ['flow_type'], unique=False)
    op.create_index(op.f('ix_external_trade_flows_partner_id'), 'external_trade_flows', ['partner_id'], unique=False)
    op.create_index(op.f('ix_external_trade_flows_reporter_id'), 'external_trade_flows', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_external_trade_flows_source'), 'external_trade_flows', ['source'], unique=False)
    op.create_index(op.f('ix_external_trade_flows_year'), 'external_trade_flows', ['year'], unique=False)
    
    op.create_table('external_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('series_ref_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('series_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period_label', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['series_ref_id'], ['external_data_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'series_id', 'date', 'period_label', name='uq_external_observation')
    )
    op.create_index(op.f('ix_external_observations_date'), 'external_observations', ['date'], unique=False)
    op.create_index(op.f('ix_external_observations_series_id'), 'external_observations', ['series_id'], unique=False)
    op.create_index(op.f('ix_external_observations_source'), 'external_observations', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_observations_source'), table_name='external_observations')
    op.drop_index(op.f('ix_external_observations_series_id'), table_name='external_observations')
    op.drop_index(op.f('ix_external_observations_date'), table_name='external_observations')
    op.drop_table('external_observations')
    op.drop_index(op.f('ix_external_trade_flows_year'), table_name='external_trade_flows')
    op.drop_index(op.f('ix_external_trade_flows_source'), table_name='external_trade_flows')
    op.drop_index(op.f('ix_external_trade_flows_reporter_id'), table_name='external_trade_flows')
    op.drop_index(op.f('ix_external_trade_flows_partner_id'), table_name='external_trade_flows')
    op.drop_index(op.f('ix_external_trade_flows_flow_type'), table_name='external_trade_flows')
    op.drop_index(op.f('ix_external_trade_flows_commodity_id'), table_name='external_trade_flows')
    op.drop_table('external_trade_flows')
    op.drop_index(op.f('ix_external_industry_stats_year'), table_name='external_industry_stats')
    op.drop_index(op.f('ix_external_industry_stats_source'), table_name='external_industry_stats')
    op.drop_index(op.f('ix_external_industry_stats_metric_name'), table_name='external_industry_stats')
    op.drop_index(op.f('ix_external_industry_stats_industry_id'), table_name='external_industry_stats')
    op.drop_index(op.f('ix_external_industry_stats_geo_id'), table_name='external_industry_stats')
    op.drop_index(op.f('ix_external_industry_stats_dataset'), table_name='external_industry_stats')
    op.drop_table('external_industry_stats')
    op.drop_index(op.f('ix_external_data_series_source'), table_name='external_data_series')
    op.drop_index(op.f('ix_external_data_series_series_id'), table_name='external_data_series')
    op.drop_table('external_data_series')
    op.drop_index(op.f('ix_external_data_fetch_logs_status'), table_name='external_data_fetch_logs')
    op.drop_index(op.f('ix_external_data_fetch_logs_source'), table_name='external_data_fetch_logs')
    op.drop_index(op.f('ix_external_data_fetch_logs_job_name'), table_name='external_data_fetch_logs')
    op.drop_table('external_data_fetch_logs')
    # ### end Alembic commands ###
