"""Add missing alert log columns

Revision ID: 546c64d1a7fb
Revises: 61e4a7b61594
Create Date: 2026-03-19 03:39:44.890477

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
revision: str = '546c64d1a7fb'
down_revision: Union[str, Sequence[str], None] = '61e4a7b61594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('event_clusters', sa.Column('id', sa.UUID(), nullable=False), sa.Column('representative_title', sa.String(), nullable=False), sa.Column('category', sa.String(), nullable=True), sa.Column('article_count', sa.Integer(), nullable=True), sa.Column('source_count', sa.Integer(), nullable=True), sa.Column('avg_signal_score', sa.Float(), nullable=True), sa.Column('metrics_json', sa.JSON(), nullable=True), sa.Column('summary_data', sa.JSON(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True), sa.PrimaryKeyConstraint('id'))
    op.create_table('job_runs', sa.Column('id', sa.UUID(), nullable=False), sa.Column('job_name', sa.String(), nullable=False), sa.Column('status', sa.String(), nullable=False), sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True), sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True), sa.Column('error_message', sa.String(), nullable=True), sa.PrimaryKeyConstraint('id'))
    op.create_table('raw_items', sa.Column('id', sa.UUID(), nullable=False), sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False), sa.Column('source_system', sa.String(), nullable=False), sa.Column('source_endpoint', sa.String(), nullable=False), sa.Column('source_id', sa.String(), nullable=True), sa.Column('source_group', sa.String(), nullable=True), sa.Column('reliability_weight', sa.Float(), nullable=True), sa.Column('payload_json', sa.JSON(), nullable=False), sa.Column('payload_hash', sa.String(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True), sa.PrimaryKeyConstraint('id'))
    op.create_table('source_registry', sa.Column('source_id', sa.String(), nullable=False), sa.Column('source_name', sa.String(), nullable=False), sa.Column('source_group', sa.String(), nullable=False), sa.Column('rss_url', sa.String(), nullable=False), sa.Column('reliability_weight', sa.Float(), nullable=False), sa.Column('enabled', sa.Boolean(), nullable=True), sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True), sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True), sa.Column('consecutive_failures', sa.Integer(), nullable=True), sa.PrimaryKeyConstraint('source_id'))
    op.create_table('topics', sa.Column('id', sa.UUID(), nullable=False), sa.Column('topic_code', sa.String(), nullable=False), sa.Column('topic_name_ja', sa.String(), nullable=True), sa.Column('topic_name_en', sa.String(), nullable=True), sa.Column('keywords', sa.JSON(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('topic_code'))
    op.create_table('article_outputs', sa.Column('id', sa.UUID(), nullable=False), sa.Column('output_type', sa.String(), nullable=True), sa.Column('article_type', sa.String(), nullable=True), sa.Column('report_id', sa.UUID(), nullable=True), sa.Column('topic_code', sa.String(), nullable=True), sa.Column('lang', sa.String(), nullable=True), sa.Column('title', sa.String(), nullable=True), sa.Column('summary', sa.String(), nullable=True), sa.Column('body_markdown', sa.String(), nullable=True), sa.Column('cta_text', sa.String(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True), sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id'))
    op.create_table('pdf_jobs', sa.Column('id', sa.UUID(), nullable=False), sa.Column('report_id', sa.UUID(), nullable=True), sa.Column('pdf_type', sa.String(), nullable=True), sa.Column('is_required', sa.Boolean(), nullable=True), sa.Column('status', sa.String(), nullable=True), sa.Column('output_path', sa.String(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True), sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id'))
    op.create_table('report_trigger_logs', sa.Column('id', sa.UUID(), nullable=False), sa.Column('topic_code', sa.String(), nullable=False), sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True), sa.Column('peak_score', sa.Float(), nullable=True), sa.Column('report_type', sa.String(), nullable=True), sa.Column('report_id', sa.UUID(), nullable=True), sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id'))
    op.create_table('source_health_logs', sa.Column('id', sa.UUID(), nullable=False), sa.Column('source_id', sa.String(), nullable=True), sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True), sa.Column('success', sa.Boolean(), nullable=False), sa.Column('entry_count', sa.Integer(), nullable=True), sa.Column('error_message', sa.String(), nullable=True), sa.ForeignKeyConstraint(['source_id'], ['source_registry.source_id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id'))
    op.create_table('analysis_cache', sa.Column('id', sa.UUID(), nullable=False), sa.Column('item_id', sa.UUID(), nullable=True), sa.Column('model_name', sa.String(), nullable=True), sa.Column('prompt_version', sa.String(), nullable=True), sa.Column('classification_result', sa.JSON(), nullable=True), sa.Column('signal_result', sa.JSON(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True), sa.Column('cache_expires_at', sa.DateTime(timezone=True), nullable=True), sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('item_id'))
    op.create_table('item_topics', sa.Column('id', sa.UUID(), nullable=False), sa.Column('item_id', sa.UUID(), nullable=True), sa.Column('topic_code', sa.String(), nullable=True), sa.Column('confidence_score', sa.Float(), nullable=True), sa.Column('matched_keywords', sa.JSON(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True), sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id'))
    op.create_table('signal_rankings', sa.Column('id', sa.UUID(), nullable=False), sa.Column('signal_type', sa.String(), nullable=True), sa.Column('period_start', sa.DateTime(timezone=True), nullable=True), sa.Column('period_end', sa.DateTime(timezone=True), nullable=True), sa.Column('rank', sa.Integer(), nullable=True), sa.Column('item_id', sa.UUID(), nullable=True), sa.Column('score', sa.Float(), nullable=True), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True), sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id'))
    op.drop_table('risk_headlining')
    op.add_column('alert_logs', sa.Column('target_label', sa.String(), nullable=False))
    op.add_column('alert_logs', sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('alert_logs', sa.Column('intensity', sa.Float(), nullable=True))
    op.add_column('alert_logs', sa.Column('section_anchor', sa.String(), nullable=True))
    op.drop_column('alert_logs', 'message')
    op.drop_column('alert_logs', 'topic')
    op.drop_column('alert_logs', 'created_at')
    op.add_column('external_posts', sa.Column('report_id', sa.UUID(), nullable=True))
    op.add_column('external_posts', sa.Column('container_id', sa.String(), nullable=True))
    op.add_column('external_posts', sa.Column('status', sa.String(), nullable=True))
    op.add_column('external_posts', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('external_posts', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('external_posts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.create_foreign_key(None, 'external_posts', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.drop_column('external_posts', 'posted_at')
    op.drop_column('external_posts', 'metrics')
    op.drop_column('external_posts', 'related_report_id')
    op.drop_column('external_posts', 'url')
    op.drop_column('external_posts', 'content_preview')
    op.add_column('items', sa.Column('type', sa.String(), nullable=True))
    op.add_column('items', sa.Column('dedup_key', sa.String(), nullable=False))
    op.add_column('items', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('items', sa.Column('source_name', sa.String(), nullable=True))
    op.add_column('items', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('items', sa.Column('source_id', sa.String(), nullable=True))
    op.add_column('items', sa.Column('source_group', sa.String(), nullable=True))
    op.add_column('items', sa.Column('reliability_weight', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('rough_category', sa.String(), nullable=True))
    op.add_column('items', sa.Column('lightweight_score', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('geo', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.create_unique_constraint(None, 'items', ['dedup_key'])
    op.create_foreign_key(None, 'items', 'event_clusters', ['cluster_id'], ['id'], ondelete='SET NULL')
    op.drop_column('items', 'risk_score')
    op.drop_column('items', 'content')
    op.drop_column('items', 'entities')
    op.drop_column('items', 'source')
    op.drop_column('items', 'intensity_score')
    op.drop_column('items', 'processed_at')
    op.drop_column('items', 'normalized_content')
    op.drop_column('items', 'url')
    op.add_column('reports', sa.Column('report_type', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('topic_code', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reports', sa.Column('period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reports', sa.Column('lang', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('model_name', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('input_items_hash', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('content_markdown', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('archive_pdf_path', sa.String(), nullable=True))
    op.drop_column('reports', 'full_markdown')
    op.drop_column('reports', 'title')
    op.drop_column('reports', 'metadata_json')
    op.drop_column('reports', 'summary')
    op.drop_column('reports', 'category')
    op.add_column('trend_signals', sa.Column('trend_type', sa.String(), nullable=False))
    op.add_column('trend_signals', sa.Column('target_label', sa.String(), nullable=False))
    op.add_column('trend_signals', sa.Column('intensity_score', sa.Float(), nullable=True))
    op.add_column('trend_signals', sa.Column('window_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trend_signals', sa.Column('window_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trend_signals', sa.Column('description', sa.String(), nullable=True))
    op.add_column('trend_signals', sa.Column('metrics_json', sa.JSON(), nullable=True))
    op.add_column('trend_signals', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_column('trend_signals', 'detected_at')
    op.drop_column('trend_signals', 'supporting_clusters')
    op.drop_column('trend_signals', 'topic')
    op.drop_column('trend_signals', 'intensity')
    op.drop_column('trend_signals', 'pattern_name')
    op.drop_column('trend_signals', 'summary')

def downgrade() -> None:
    """Downgrade schema."""
    op.add_column('trend_signals', sa.Column('summary', sa.VARCHAR(), nullable=True))
    op.add_column('trend_signals', sa.Column('pattern_name', sa.VARCHAR(), nullable=True))
    op.add_column('trend_signals', sa.Column('intensity', sa.FLOAT(), nullable=True))
    op.add_column('trend_signals', sa.Column('topic', sa.VARCHAR(), nullable=True))
    op.add_column('trend_signals', sa.Column('supporting_clusters', sqlite.JSON(), nullable=True))
    op.add_column('trend_signals', sa.Column('detected_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_column('trend_signals', 'created_at')
    op.drop_column('trend_signals', 'metrics_json')
    op.drop_column('trend_signals', 'description')
    op.drop_column('trend_signals', 'window_end')
    op.drop_column('trend_signals', 'window_start')
    op.drop_column('trend_signals', 'intensity_score')
    op.drop_column('trend_signals', 'target_label')
    op.drop_column('trend_signals', 'trend_type')
    op.add_column('reports', sa.Column('category', sa.VARCHAR(), nullable=True))
    op.add_column('reports', sa.Column('summary', sa.VARCHAR(), nullable=True))
    op.add_column('reports', sa.Column('metadata_json', sqlite.JSON(), nullable=True))
    op.add_column('reports', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.add_column('reports', sa.Column('full_markdown', sa.VARCHAR(), nullable=True))
    op.drop_column('reports', 'archive_pdf_path')
    op.drop_column('reports', 'content_markdown')
    op.drop_column('reports', 'input_items_hash')
    op.drop_column('reports', 'model_name')
    op.drop_column('reports', 'lang')
    op.drop_column('reports', 'period_end')
    op.drop_column('reports', 'period_start')
    op.drop_column('reports', 'topic_code')
    op.drop_column('reports', 'report_type')
    op.add_column('items', sa.Column('url', sa.VARCHAR(), nullable=True))
    op.add_column('items', sa.Column('normalized_content', sa.VARCHAR(), nullable=True))
    op.add_column('items', sa.Column('processed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('items', sa.Column('intensity_score', sa.FLOAT(), nullable=True))
    op.add_column('items', sa.Column('source', sa.VARCHAR(), nullable=True))
    op.add_column('items', sa.Column('entities', sqlite.JSON(), nullable=True))
    op.add_column('items', sa.Column('content', sa.VARCHAR(), nullable=True))
    op.add_column('items', sa.Column('risk_score', sa.FLOAT(), nullable=True))
    op.drop_column('items', 'created_at')
    op.drop_column('items', 'tags')
    op.drop_column('items', 'geo')
    op.drop_column('items', 'lightweight_score')
    op.drop_column('items', 'rough_category')
    op.drop_column('items', 'reliability_weight')
    op.drop_column('items', 'source_group')
    op.drop_column('items', 'source_id')
    op.drop_column('items', 'source_url')
    op.drop_column('items', 'source_name')
    op.drop_column('items', 'summary')
    op.drop_column('items', 'dedup_key')
    op.drop_column('items', 'type')
    op.add_column('external_posts', sa.Column('content_preview', sa.VARCHAR(), nullable=True))
    op.add_column('external_posts', sa.Column('url', sa.VARCHAR(), nullable=True))
    op.add_column('external_posts', sa.Column('related_report_id', sa.NUMERIC(), nullable=True))
    op.add_column('external_posts', sa.Column('metrics', sqlite.JSON(), nullable=True))
    op.add_column('external_posts', sa.Column('posted_at', sa.DATETIME(), nullable=True))
    op.create_foreign_key(None, 'external_posts', 'reports', ['related_report_id'], ['id'], ondelete='SET NULL')
    op.drop_column('external_posts', 'created_at')
    op.drop_column('external_posts', 'published_at')
    op.drop_column('external_posts', 'error_message')
    op.drop_column('external_posts', 'status')
    op.drop_column('external_posts', 'container_id')
    op.drop_column('external_posts', 'report_id')
    op.add_column('alert_logs', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('alert_logs', sa.Column('topic', sa.VARCHAR(), nullable=True))
    op.add_column('alert_logs', sa.Column('message', sa.VARCHAR(), nullable=True))
    op.drop_column('alert_logs', 'section_anchor')
    op.drop_column('alert_logs', 'intensity')
    op.drop_column('alert_logs', 'triggered_at')
    op.drop_column('alert_logs', 'target_label')
    op.create_table('risk_headlining', sa.Column('id', sa.NUMERIC(), nullable=False), sa.Column('cluster_id', sa.VARCHAR(), nullable=True), sa.Column('headline_en', sa.VARCHAR(), nullable=True), sa.Column('headline_jp', sa.VARCHAR(), nullable=True), sa.Column('impact_score', sa.FLOAT(), nullable=True), sa.Column('geopolitical_context', sa.VARCHAR(), nullable=True), sa.Column('last_updated', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True), sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('cluster_id'))
    op.drop_table('signal_rankings')
    op.drop_table('item_topics')
    op.drop_table('analysis_cache')
    op.drop_table('source_health_logs')
    op.drop_table('report_trigger_logs')
    op.drop_table('pdf_jobs')
    op.drop_table('article_outputs')
    op.drop_table('topics')
    op.drop_table('source_registry')
    op.drop_table('raw_items')
    op.drop_table('job_runs')
    op.drop_table('event_clusters')