"""Add stripe columns

Revision ID: 61e4a7b61594
Revises: 626999057fb2
Create Date: 2026-03-18 20:57:29.529782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e4a7b61594'
down_revision: Union[str, Sequence[str], None] = '626999057fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyst_profiles', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('analyst_profiles', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyst_profiles', 'stripe_subscription_id')
    op.drop_column('analyst_profiles', 'stripe_customer_id')
    # ### end Alembic commands ###
