"""add_bea_nipa_observations

Revision ID: 6efb682db860
Revises: ce69929fa098
Create Date: 2026-05-05 17:52:10.755529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efb682db860'
down_revision: Union[str, Sequence[str], None] = 'ce69929fa098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bea_nipa_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_name', sa.String(length=64), nullable=False),
    sa.Column('table_name', sa.String(length=16), nullable=False),
    sa.Column('series_code', sa.String(length=16), nullable=True),
    sa.Column('line_number', sa.String(length=8), nullable=False),
    sa.Column('line_description', sa.String(length=256), nullable=True),
    sa.Column('time_period', sa.String(length=16), nullable=False),
    sa.Column('frequency', sa.String(length=4), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=True),
    sa.Column('cl_unit', sa.String(length=64), nullable=True),
    sa.Column('unit_mult', sa.Integer(), nullable=True),
    sa.Column('data_value', sa.Float(), nullable=True),
    sa.Column('note_ref', sa.String(length=32), nullable=True),
    sa.Column('statistic', sa.String(length=128), nullable=True),
    sa.Column('utc_production_time', sa.String(length=32), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_name', 'table_name', 'line_number', 'time_period', 'frequency', name='uq_bea_nipa_data_point')
    )
    op.create_index('ix_bea_nipa_fetched_at', 'bea_nipa_observations', ['fetched_at'], unique=False)
    op.create_index('ix_bea_nipa_series_code', 'bea_nipa_observations', ['series_code'], unique=False)
    op.create_index('ix_bea_nipa_table_line', 'bea_nipa_observations', ['table_name', 'line_number'], unique=False)
    op.create_index('ix_bea_nipa_table_period', 'bea_nipa_observations', ['table_name', 'time_period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bea_nipa_table_period', table_name='bea_nipa_observations')
    op.drop_index('ix_bea_nipa_table_line', table_name='bea_nipa_observations')
    op.drop_index('ix_bea_nipa_series_code', table_name='bea_nipa_observations')
    op.drop_index('ix_bea_nipa_fetched_at', table_name='bea_nipa_observations')
    op.drop_table('bea_nipa_observations')
    # ### end Alembic commands ###
