"""Add dedicated spatial engine tables

Revision ID: 8d599ede075c
Revises: c9d1b3e7f2a4
Create Date: 2026-05-27 11:53:53.242322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d599ede075c'
down_revision: Union[str, Sequence[str], None] = 'c9d1b3e7f2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contagion_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.String(), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nodes_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edges_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entropy_index', sa.Float(), nullable=False),
    sa.Column('viscosity_coefficient', sa.Float(), nullable=False),
    sa.Column('phase_transition_warning', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contagion_history_domain_ts', 'contagion_history', ['domain_id', 'snapshot_timestamp'], unique=False)
    op.create_table('spatial_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.String(), nullable=False),
    sa.Column('source_lon', sa.Float(), nullable=False),
    sa.Column('source_lat', sa.Float(), nullable=False),
    sa.Column('target_lon', sa.Float(), nullable=False),
    sa.Column('target_lat', sa.Float(), nullable=False),
    sa.Column('edge_intensity', sa.Float(), nullable=False),
    sa.Column('viscosity_coefficient', sa.Float(), nullable=False),
    sa.Column('order_level', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_spatial_edges_domain_id', 'spatial_edges', ['domain_id'], unique=False)
    op.create_index('ix_spatial_edges_domain_order', 'spatial_edges', ['domain_id', 'order_level'], unique=False)
    op.create_table('spatial_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('entropy_index', sa.Float(), nullable=False),
    sa.Column('is_epicenter', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_spatial_nodes_domain_id', 'spatial_nodes', ['domain_id'], unique=False)
    op.create_index('ix_spatial_nodes_domain_updated', 'spatial_nodes', ['domain_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spatial_nodes_domain_updated', table_name='spatial_nodes')
    op.drop_index('ix_spatial_nodes_domain_id', table_name='spatial_nodes')
    op.drop_table('spatial_nodes')
    op.drop_index('ix_spatial_edges_domain_order', table_name='spatial_edges')
    op.drop_index('ix_spatial_edges_domain_id', table_name='spatial_edges')
    op.drop_table('spatial_edges')
    op.drop_index('ix_contagion_history_domain_ts', table_name='contagion_history')
    op.drop_table('contagion_history')
    # ### end Alembic commands ###
