"""add_bls_ppi_observations

Revision ID: eeb4fdd8ebff
Revises: 6efb682db860
Create Date: 2026-05-05 18:12:26.204110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb4fdd8ebff'
down_revision: Union[str, Sequence[str], None] = '6efb682db860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bls_ppi_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('dataset_name', sa.String(length=32), nullable=False),
    sa.Column('series_id', sa.String(length=32), nullable=False),
    sa.Column('series_name', sa.String(length=256), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=4), nullable=False),
    sa.Column('period_name', sa.String(length=16), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('footnotes', sa.JSON(), nullable=True),
    sa.Column('latest', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'dataset_name', 'series_id', 'date', name='uq_bls_ppi_data_point')
    )
    op.create_index('ix_bls_ppi_date', 'bls_ppi_observations', ['date'], unique=False)
    op.create_index('ix_bls_ppi_fetched_at', 'bls_ppi_observations', ['fetched_at'], unique=False)
    op.create_index('ix_bls_ppi_latest', 'bls_ppi_observations', ['latest'], unique=False)
    op.create_index('ix_bls_ppi_series_date', 'bls_ppi_observations', ['series_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bls_ppi_series_date', table_name='bls_ppi_observations')
    op.drop_index('ix_bls_ppi_latest', table_name='bls_ppi_observations')
    op.drop_index('ix_bls_ppi_fetched_at', table_name='bls_ppi_observations')
    op.drop_index('ix_bls_ppi_date', table_name='bls_ppi_observations')
    op.drop_table('bls_ppi_observations')
    # ### end Alembic commands ###
