import os
import sys
import shutil
import logging
import argparse
import json
from datetime import datetime, timedelta, timezone
import asyncio
import re

# Add root to sys.path
sys.path.append(os.getcwd())

from sqlalchemy.future import select
from db.database import AsyncSessionLocal
from db.models import Report, AlertLog

# Constants
DEFAULT_RETENTION_DAYS = 14
SAFETY_WINDOW_DAYS = 7
MAX_DELETE_PER_RUN = 50

# Setup Logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class VisualAudit:
    def __init__(self, dry_run=True, archive_only=False, retention_days=DEFAULT_RETENTION_DAYS):
        self.dry_run = dry_run
        self.archive_only = archive_only
        self.retention_days = retention_days
        
        self.base_dir = os.getcwd()
        self.visuals_dir = os.path.join(self.base_dir, "outputs", "visuals")
        self.archive_dir = os.path.join(self.base_dir, "outputs", "archive")
        self.outputs_dir = os.path.join(self.base_dir, "outputs")
        
        os.makedirs(self.archive_dir, exist_ok=True)
        
        self.referenced_files = set()
        self.all_files = []
        self.stats = {
            "total_scanned": 0,
            "referenced": 0,
            "unreferenced_recent": 0,
            "unreferenced_old": 0,
            "legacy_pattern": 0,
            "uncertain": 0,
            "archived": 0,
            "deleted": 0,
            "skipped": 0,
            "reclaimed_mb": 0.0
        }

    async def build_reference_map(self):
        """Query DB and local files for any mention of visual filenames."""
        logger.info("Building reference map...")
        
        async with AsyncSessionLocal() as db:
            # 1. Query Reports
            stmt_reports = select(Report.content_markdown, Report.teaser_md)
            reports = (await db.execute(stmt_reports)).all()
            for r_content, r_teaser in reports:
                self._extract_from_text(r_content)
                self._extract_from_text(r_teaser)
            
            # 2. Query AlertLog metadata
            stmt_alerts = select(AlertLog.metadata_json)
            alerts = (await db.execute(stmt_alerts)).scalars().all()
            for meta in alerts:
                if meta:
                    self._extract_from_text(json.dumps(meta))
        
        # 3. Scan outputs directory for markdown files
        for root, dirs, files in os.walk(self.outputs_dir):
            if "visuals" in root or "archive" in root: continue
            for file in files:
                if file.endswith(".md"):
                    try:
                        with open(os.path.join(root, file), 'r', encoding='utf-8') as f:
                            self._extract_from_text(f.read())
                    except Exception as e:
                        logger.warning(f"Could not read markdown file {file}: {e}")

        logger.info(f"Found {len(self.referenced_files)} unique referenced visuals.")

    def _extract_from_text(self, text):
        if not text: return
        # Pattern matches filenames like visual_topic_date_hash_metric.png
        # Specifically looking for the ones generated by visual_engine.py
        matches = re.findall(r'visual_[a-zA-Z0-9_]+\.png', text)
        for m in matches:
            self.referenced_files.add(m)

    def classify_and_process(self):
        """Main classification and execution loop."""
        if not os.path.exists(self.visuals_dir):
            logger.warning(f"Visuals directory not found: {self.visuals_dir}")
            return
            
        self.all_files = [f for f in os.listdir(self.visuals_dir) if f.endswith(".png")]
        self.stats["total_scanned"] = len(self.all_files)
        
        now = datetime.now()
        candidates_for_deletion = []

        for filename in self.all_files:
            file_path = os.path.join(self.visuals_dir, filename)
            mtime = datetime.fromtimestamp(os.path.getmtime(file_path))
            age_days = (now - mtime).days
            size_mb = os.path.getsize(file_path) / (1024 * 1024)
            
            # Classification
            is_referenced = filename in self.referenced_files
            is_recent = age_days <= SAFETY_WINDOW_DAYS
            is_aged = age_days > self.retention_days
            
            # Pattern check (Legacy check)
            # Current pattern: visual_{topic}_{date}_{id/desc}_{type}.png
            # Anything else might be legacy
            is_legacy = not (filename.startswith("visual_") and filename.endswith(".png"))
            
            if is_referenced:
                self.stats["referenced"] += 1
                status = "REFERENCED"
            elif is_recent:
                self.stats["unreferenced_recent"] += 1
                status = "KEEP (RECENT)"
            elif is_aged:
                if is_legacy:
                    self.stats["legacy_pattern"] += 1
                    status = "ARCHIVE (LEGACY)"
                    self._archive_file(filename, size_mb)
                elif self._is_uncertain(filename):
                    self.stats["uncertain"] += 1
                    status = "ARCHIVE (UNCERTAIN)"
                    self._archive_file(filename, size_mb)
                else:
                    self.stats["unreferenced_old"] += 1
                    status = "DELETE CANDIDATE"
                    candidates_for_deletion.append((filename, size_mb))
            else:
                self.stats["referenced"] += 0 # Fallthrough for unreferenced but within retention
                status = "KEEP (WITHIN RETENTION)"
                self.stats["skipped"] += 1

            logger.debug(f"{filename} | Age: {age_days}d | Status: {status}")

        # Safety Guard 1: Deletion Limit
        if len(candidates_for_deletion) > MAX_DELETE_PER_RUN:
            logger.warning(f"!!! SAFETY LIMIT REACHED !!! Candidates ({len(candidates_for_deletion)}) exceed MAX_DELETE_PER_RUN ({MAX_DELETE_PER_RUN}).")
            logger.warning("Aborting deletion to prevent potential mass loss. Please check classification logs.")
            self.stats["skipped"] += len(candidates_for_deletion)
            # Force archive mode for these if not in dry run? No, just stop and report.
            return

        # Phase 3: Final Reference Check + Deletion
        for filename, size_mb in candidates_for_deletion:
            if self.archive_only:
                self._archive_file(filename, size_mb)
            elif not self.dry_run:
                # Safety Guard 2: Final Reference Check against last 7 days of reports
                # (Already somewhat covered by build_reference_map, but this is the defensive layer)
                if self._final_defensive_check(filename):
                    logger.info(f"Safety Guard 2 triggered for {filename}. Skipping deletion.")
                    self.stats["skipped"] += 1
                    continue
                    
                self._delete_file(filename, size_mb)
            else:
                logger.info(f"[DRY-RUN] Would delete: {filename} ({size_mb:.2f} MB)")
                self.stats["reclaimed_mb"] += size_mb

    def _is_uncertain(self, filename):
        # Example logic: if filename doesn't follow expected pattern or has weird chars
        # For now, if it doesn't match the common generated patterns:
        if not re.match(r'visual_[a-z_]+_\d{8}_[a-z0-9_]+\.png', filename):
            return True
        return False

    def _final_defensive_check(self, filename):
        # This is a synchronous check for safety
        # In a real app, this might re-query the latest DB records
        # Since we already did this in build_reference_map, we'll double check if anything was missed
        # or if referenced_files changed.
        return filename in self.referenced_files

    def _archive_file(self, filename, size_mb):
        src = os.path.join(self.visuals_dir, filename)
        dst = os.path.join(self.archive_dir, filename)
        if self.dry_run:
            logger.info(f"[DRY-RUN] Would archive: {filename}")
        else:
            try:
                shutil.move(src, dst)
                logger.info(f"Archived: {filename}")
                self.stats["archived"] += 1
            except Exception as e:
                logger.error(f"Failed to archive {filename}: {e}")

    def _delete_file(self, filename, size_mb):
        file_path = os.path.join(self.visuals_dir, filename)
        try:
            os.remove(file_path)
            logger.info(f"Deleted: {filename}")
            self.stats["deleted"] += 1
            self.stats["reclaimed_mb"] += size_mb
        except Exception as e:
            logger.error(f"Failed to delete {filename}: {e}")

    def report(self):
        logger.info("--- Cleanup Audit Report ---")
        for k, v in self.stats.items():
            logger.info(f"{k.replace('_', ' ').capitalize()}: {v}")
        logger.info("----------------------------")

async def run_visual_cleanup(dry_run=False, archive_only=False, retention=DEFAULT_RETENTION_DAYS):
    """Entry point for the scheduler."""
    logger.info(f"Starting Visual Asset Cleanup (dry_run={dry_run}, archive_only={archive_only}, retention={retention})")
    audit = VisualAudit(dry_run=dry_run, archive_only=archive_only, retention_days=retention)
    await audit.build_reference_map()
    audit.classify_and_process()
    audit.report()

async def main():
    parser = argparse.ArgumentParser(description="Audit and clean up unused visual assets.")
    parser.add_argument("--dry-run", action="store_true", help="Report only, no changes.")
    parser.add_argument("--archive-only", action="store_true", help="Archive instead of delete.")
    parser.add_argument("--retention", type=int, default=DEFAULT_RETENTION_DAYS, help="Retention days.")
    parser.add_argument("--verbose", action="store_true", help="Enable debug logging.")
    
    args = parser.parse_args()
    
    if args.verbose:
        logger.setLevel(logging.DEBUG)
    
    audit = VisualAudit(dry_run=args.dry_run, archive_only=args.archive_only, retention_days=args.retention)
    await audit.build_reference_map()
    audit.classify_and_process()
    audit.report()

if __name__ == "__main__":
    asyncio.run(main())
